name: Haskell Autotag
author: Simon Hengel
description: Create a Git tag on `.cabal` version bumps

branding:
  icon: tag
  color: white

inputs:
  package-path:
    default: .

  prefix:
    default: v

  pre-releases:
    default: false

  dry-run:
    default: false

outputs:
  created:
    value: ${{ steps.autotag.outputs.created }}

  name:
    value: ${{ steps.autotag.outputs.name }}

  version:
    value: ${{ steps.autotag.outputs.version }}

  version-tags:
    value: ${{ steps.autotag.outputs.version-tags }}

  version-with-tags:
    value: ${{ steps.autotag.outputs.version-with-tags }}

runs:
  using: composite
  steps:
    - shell: bash
      run: git fetch --tags 2> /dev/null
    - shell: bash
      run: '"$(dirname $(readlink --canonicalize $(which ghc)))/runhaskell" ${{ github.action_path }}/src/Autotag.hs'
      id: autotag
      env:
        AUTOTAG_PREFIX: ${{ inputs.prefix }}
        AUTOTAG_PACKAGE_PATH: ${{ inputs.package-path }}
        AUTOTAG_PRE_RELEASES: ${{ inputs.pre-releases }}
        AUTOTAG_DRY_RUN: ${{ inputs.dry-run }}

    - shell: bash
      run: |
        echo ::group::outputs
        echo "created: ${{ steps.autotag.outputs.created }}"
        echo "name: ${{ steps.autotag.outputs.name }}"
        echo "version: ${{ steps.autotag.outputs.version }}"
        echo "version-tags: ${{ steps.autotag.outputs.version-tags }}"
        echo "version-with-tags: ${{ steps.autotag.outputs.version-with-tags }}"
        echo ::endgroup::
