name: autotag

copyright: (c) 2020-2021 Simon Hengel
author: Simon Hengel <sol@typeful.net>

ghc-options: -Wall

dependencies:
  - base == 4.*
  - directory
  - filepath
  - process

library:
  source-dirs: src

executables:
  git-tag:
    main: driver/Main.hs
    dependencies:
      - autotag

tests:
  spec:
    build-tools: hspec-discover
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - autotag
      - hspec == 2.*
      - mockery
      - silently
